{% set name = "conda-inject" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/conda_inject-{{ version }}.tar.gz
  sha256: 0b8cde8c47998c118d8ff285a04977a3abcf734caf579c520fca469df1cd0aac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - pyyaml >=6.0.0,<7.0.0

test:
  imports:
    - conda_inject
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Helper functions for injecting a conda environment into the current python environment (by modifying sys.path, without actually changing the current python environment).
  home: https://github.com/koesterlab/conda-inject
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
